

---
driver:
  name: "terraform"
  command_timeout: 1800

provisioner:
  name: terraform

platforms:
  - name: terraform

suites:
  - name: default
    driver:
      name: terraform
      command_timeout: 1800
      root_module_directory: test/fixtures/default/
    verifier:
      name: inspec
      color: false
      systems:
        - name: default
          backend: local
          controls:
            - gcloud
            - gcloud_dataflow
            - gsutil

